Oriented overset updates
NaluCFD/Nalu pull request #533
Opened 2021-04-06 20:02 UTC by wjhorne

Includes : 

- Removal of TIOGA TPL
- Upgrade to STK assembly including oriented shape cutting + documentation
- Bug fixes for 6-DOF motion 
- Name shift from orphan terminology to constraint terminology.

2021-04-06 20:08 UTC, spdomin commented
@wjhorne, this looks good. However, before we squash and merge, let's work through the Trilinos diffs/bi-sect first.

2021-04-12 15:35 UTC, spdomin commented on docs/requirements.txt
> +Pygments==2.3.1
I think that this needs to be 2.7.4. Not sure how the merge did not deal with this automatically?

2021-04-12 15:36 UTC, spdomin commented on src/AssembleMomentumElemSolverAlgorithm.C
> +          //const double ui = 0.5*(p_vrtm[ilNdim+i] + p_vrtm[irNdim+i]);
Try to remove old comments..

2021-04-12 15:37 UTC, spdomin commented on src/Realm.C
> +        vnp1[offSet+i] = (uX[i]+motion.bodyVel_[i]);
Might only be style...

2021-04-12 15:38 UTC, spdomin commented on src/kernel/VolumeOfFluidSucvNsoElemKernel.C
> +        w_uIpv[j] += r*v_v(ic,j);
Not needed now?

2021-04-12 15:38 UTC, spdomin commented on src/kernel/VolumeOfFluidSucvNsoElemKernel.C
> +  NALU_ALIGNED DoubleType w_uIpv[AlgTraits::nDim_];
Not needed now?

2021-04-12 15:38 UTC, spdomin commented on src/kernel/VolumeOfFluidSucvNsoElemKernel.C
> +  // NEW WJH
WIP... Probably can remove..

2021-04-12 15:39 UTC, spdomin requested changes
This looks good. I think you only have a few WIP comments/code snippets to remove. 

Once that is done, we can approve..

2021-04-12 15:40 UTC, wjhorne commented
Sounds good. I'll clean this all up. Thank you for reviewing it

2021-04-12 17:09 UTC, wjhorne commented
I found that many of these suggested changes were from the first commit out of the two that were initially in the PR. The second commit had already fixed many of the WIP issues. There was one remaining WIP line found that still needed to be removed and has now been removed. I believe all changes have now been accounted for.

2021-04-12 19:04 UTC, spdomin commented
Looks good. Most times I squash my commits prior to a PR. In the end, I squash them anyway during the merge.

Next time, I will look more carefully.

2021-04-12 19:04 UTC, merged